name: Build DEB Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dpkg
        run: sudo apt update && sudo apt install -y dpkg-dev

      - name: Fix permissions
        run: |
          chmod 0755 DEBIAN/postinst
          chmod 0644 DEBIAN/control

      - name: Build .deb
        run: dpkg-deb -b . payload.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: payload-deb
          path: payload.deb
